FROM golang:latest

WORKDIR /go/src/github.com/e-lostar/swoworkshop/

COPY . .

RUN go get github.com/gorilla/mux && go get github.com/prometheus/client_golang/prometheus/promhttp

ENTRYPOINT ["go", "test", "-v", "./...", "-coverprofile", "cover.out"]